pipeline {
  agent {
    docker { image 'openjdk:11-jdk-slim' }
  }
  stages {
    stage('Checkout') {
      steps {
        // Git checkout happens automatically since your Jenkinsfile is inside the repo
        echo 'Code checked out'
      }
    }
    stage('Compile') {
      steps {
        dir('my-first-pipeline') {
          sh 'javac HelloWorld.java'
        }
      }
    }
    stage('Run') {
      steps {
        dir('my-first-pipeline') {
          sh 'java HelloWorld'
        }
      }
    }
  }
}
