pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Compile') {
      steps {
        sh 'javac HelloWorld.java'
      }
    }
  }
  stages {
    stage('Run') {
      steps {
        sh 'java HelloWorld'
      }
    }
  }
}
